[tool.poetry]
name = "kotizoj"
version = "0.1.0"
description = "Pessoal Finance Applications"
authors = ["Leonardo Santos <leoss33@outlook.com.br>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
yfinance = "^0.2.32"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.3"
black = "^23.11.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
